capital:
    security_token: ENC[AES256_GCM,data:wf5phHGddbgJfg3GlhLp2g==,iv:MdQFs1u/jhZsOF0d98wdj18NvLOJV2pGdgALRMEwIKo=,tag:XJtg8X+FjstK/pP1k+20NQ==,type:str]
    password: ENC[AES256_GCM,data:swXjLtqbUXQxTbgOGnol6Ha9o7Wyem2z/w==,iv:q7PmRO+wxucR5S+49zy2yFXUqSjO8ONOIuKH1pseO30=,tag:I3UxJ5hKq7n4Bnpr70+p5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mryhjfrskxfkrag8e3v5c2rucrmuw9gruah2y9m57jf0plrutacsxsfe5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeVpxM1Y4QUo3Ty9pY3NV
            em9HWkFMMUdDQ2hzcmY2QmF5YVNjNnVSTzFJCkxyUnFGUHBZSllQNmhQVzVhUnFl
            RUFKcnA1dkFjRXo3UDRVKzVyQmdaSlkKLS0tIHhsa1hodDlmVU5jWk16VDU0RjFP
            bzNBaG53bWxJTkJXY2V4cmhwQ1RHSkEKiATl35xIGvYuiaeEmV9/CYyD/Gw7Ldcp
            mIWlqt/d3E9//P9GYav3EFq7xvWxjDCHdLcW/arVX3q7T2ICYtxmKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-01T19:50:31Z"
    mac: ENC[AES256_GCM,data:5CydQ2vG4SbTm+Fb49jA/A1xJCwDKlJRJyUS8LS8DcTMaktX3z1cTnWvV1UGyTYNgc/pkopLr/VawXGfIRggkD07mG1u0tRdENiPZuGyXXFMMBrjJoWDO2NlA4472mXckpa7nXgLJZ3WmHKnySCH3GNLSJ3W6sRp8GZhU2nXc8c=,iv:qh9NavUOsaFtHWeAJj40HHZcR4Qo+Lf1w4eVPiWqFQ4=,tag:cEFeZCLixx7MErwyIniQ5Q==,type:str]
    pgp:
        - created_at: "2023-05-01T19:50:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DNrzYKOQ8z3gSAQdAr6q0dud81L0ZiII7zOwdIfwD2l9yKfeSv6XI9gfBPz4w
            nZvY8v9soLtQX4IH+RyZAMqxq+fanCTYxfnG/WpxWB2YT8BYN+0/pmVjhhcvqTs8
            0l4BkD5ISPVPWDbaYnzN2ADw+Ne6WIsZBgfmfKva13OPKQeb7I3ns3WKBi3C97fl
            PKGj2XJI8RWvOeCQhXVaR5xDy5Wifjyxt6PB5E0ercsWXflfg3VnN4AHd2vSe7M6
            =j5rO
            -----END PGP MESSAGE-----
          fp: E487A740E6312E16061F37E3E5A7009793E5E93B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
