capital:
    api_key: ENC[AES256_GCM,data:ShxUCbXjgFa0w5yVwYtoSQ==,iv:adNkpq+du5Z0ikFtH7OIIxsf7LcYGRIBi9aXfAC15rU=,tag:+xTEnhuEf0kpdiOvZln7Xw==,type:str]
    password: ENC[AES256_GCM,data:swXjLtqbUXQxTbgOGnol6Ha9o7Wyem2z/w==,iv:q7PmRO+wxucR5S+49zy2yFXUqSjO8ONOIuKH1pseO30=,tag:I3UxJ5hKq7n4Bnpr70+p5A==,type:str]
    identifier: ENC[AES256_GCM,data:NYZxJwWZT/wZ+oaP2BjYot65iIymVYElTOa4,iv:4db6eI0Ga1X0FYomc6tGiTKubLeAQmrO+tYe2Unn4gI=,tag:xva1PDKOtOU1Nk3cl+tfdw==,type:str]
symbol: ENC[AES256_GCM,data:fuiH1Q==,iv:HX6UzmF+jXKkDjTK58LBq8A0FryU/6cNnt9H8JoCk5w=,tag:LcCR0kvbs+rIhtSUP1nFvw==,type:str]
atr:
    multiplier: ENC[AES256_GCM,data:YGA=,iv:wQbWCIWNmWLwLiODMytfnxR2raqPLVXCqaY6nFc2jDg=,tag:0qXLw/7VC/bfM0NqAPu96w==,type:int]
    period: ENC[AES256_GCM,data:jA==,iv:S6ZVFrarp3It7nUF0Cuai3BDy3Qss78p53iM80jtg68=,tag:lSSQ/R+KrG+G/mrVUMSdzQ==,type:int]
start: ENC[AES256_GCM,data:A6NjjWl90p8Rmu17dEb+dSnZxw==,iv:m09agovy4A7SGVoSjCS7H+tfUNWH+GV0yhCnWpGV1V4=,tag:J5YV/pFsIfZGyNXbL1+fJQ==,type:str]
end: ENC[AES256_GCM,data:mu7jfgN57KjfB2aAVg5eZK8y2w==,iv:p/+V45aAFIcGEOpdxhv54f0MQO7oozbXtoVR3uOvY6g=,tag:eWpYZY2+gQpeWYRCMRl4pw==,type:str]
mode: ENC[AES256_GCM,data:syiyeTEQUXA=,iv:lIpMQ6ONtUefM/SbbR3P3CVg0RtkBERchwjwIiLC0X8=,tag:NtViFuf0ftwj04T7g3RJXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mryhjfrskxfkrag8e3v5c2rucrmuw9gruah2y9m57jf0plrutacsxsfe5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeVpxM1Y4QUo3Ty9pY3NV
            em9HWkFMMUdDQ2hzcmY2QmF5YVNjNnVSTzFJCkxyUnFGUHBZSllQNmhQVzVhUnFl
            RUFKcnA1dkFjRXo3UDRVKzVyQmdaSlkKLS0tIHhsa1hodDlmVU5jWk16VDU0RjFP
            bzNBaG53bWxJTkJXY2V4cmhwQ1RHSkEKiATl35xIGvYuiaeEmV9/CYyD/Gw7Ldcp
            mIWlqt/d3E9//P9GYav3EFq7xvWxjDCHdLcW/arVX3q7T2ICYtxmKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T20:46:38Z"
    mac: ENC[AES256_GCM,data:tQ6zzzFBN5cQ0E5Kw28FH7U9KYX2MTitts3KRRQGnR45RebNIWo3cq6/HKnC4e//JCN/8pCd9qPwCMEQ8p4Uq9KRo9q78O6+iJnV+ed/y0C834hx9Iqsp9VoJ0nDwXjVGCY1VbMCbXJRvlAb3snaoSKQbtdtGkNKbiR6xKs0JZE=,iv:wNLNjRsBL5BLNA0hkpVEACIUdSEv2GMG09E0ePMrYDg=,tag:uvo724dWsfapH1i+e8xr1A==,type:str]
    pgp:
        - created_at: "2023-05-01T19:50:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DNrzYKOQ8z3gSAQdAr6q0dud81L0ZiII7zOwdIfwD2l9yKfeSv6XI9gfBPz4w
            nZvY8v9soLtQX4IH+RyZAMqxq+fanCTYxfnG/WpxWB2YT8BYN+0/pmVjhhcvqTs8
            0l4BkD5ISPVPWDbaYnzN2ADw+Ne6WIsZBgfmfKva13OPKQeb7I3ns3WKBi3C97fl
            PKGj2XJI8RWvOeCQhXVaR5xDy5Wifjyxt6PB5E0ercsWXflfg3VnN4AHd2vSe7M6
            =j5rO
            -----END PGP MESSAGE-----
          fp: E487A740E6312E16061F37E3E5A7009793E5E93B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
