capital:
    api_key: ENC[AES256_GCM,data:ShxUCbXjgFa0w5yVwYtoSQ==,iv:adNkpq+du5Z0ikFtH7OIIxsf7LcYGRIBi9aXfAC15rU=,tag:+xTEnhuEf0kpdiOvZln7Xw==,type:str]
    password: ENC[AES256_GCM,data:swXjLtqbUXQxTbgOGnol6Ha9o7Wyem2z/w==,iv:q7PmRO+wxucR5S+49zy2yFXUqSjO8ONOIuKH1pseO30=,tag:I3UxJ5hKq7n4Bnpr70+p5A==,type:str]
    identifier: ENC[AES256_GCM,data:NYZxJwWZT/wZ+oaP2BjYot65iIymVYElTOa4,iv:4db6eI0Ga1X0FYomc6tGiTKubLeAQmrO+tYe2Unn4gI=,tag:xva1PDKOtOU1Nk3cl+tfdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mryhjfrskxfkrag8e3v5c2rucrmuw9gruah2y9m57jf0plrutacsxsfe5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeVpxM1Y4QUo3Ty9pY3NV
            em9HWkFMMUdDQ2hzcmY2QmF5YVNjNnVSTzFJCkxyUnFGUHBZSllQNmhQVzVhUnFl
            RUFKcnA1dkFjRXo3UDRVKzVyQmdaSlkKLS0tIHhsa1hodDlmVU5jWk16VDU0RjFP
            bzNBaG53bWxJTkJXY2V4cmhwQ1RHSkEKiATl35xIGvYuiaeEmV9/CYyD/Gw7Ldcp
            mIWlqt/d3E9//P9GYav3EFq7xvWxjDCHdLcW/arVX3q7T2ICYtxmKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-01T20:20:23Z"
    mac: ENC[AES256_GCM,data:IS0QZckLAiFYy8XTBdJg5EOCckT2a2gQXjTsMgxshxunxlXw8Wsz6dr6/2u95kvj4+XbjGP9HD3b40uPWVIV6IXSH00fKN8vvdSJpHxqo+SXjHPJZ8LCVrYsEzqkPlF/0o5zG7nIAPthEgxU3HKidD31CNryE7mqEQfFQ+izdmc=,iv:XyxZVfZaso3tfssETNwhURXpYgETgj2JkVHN1nGKKbs=,tag:JmXlrAPWEfzL3PcWDUyjMg==,type:str]
    pgp:
        - created_at: "2023-05-01T19:50:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DNrzYKOQ8z3gSAQdAr6q0dud81L0ZiII7zOwdIfwD2l9yKfeSv6XI9gfBPz4w
            nZvY8v9soLtQX4IH+RyZAMqxq+fanCTYxfnG/WpxWB2YT8BYN+0/pmVjhhcvqTs8
            0l4BkD5ISPVPWDbaYnzN2ADw+Ne6WIsZBgfmfKva13OPKQeb7I3ns3WKBi3C97fl
            PKGj2XJI8RWvOeCQhXVaR5xDy5Wifjyxt6PB5E0ercsWXflfg3VnN4AHd2vSe7M6
            =j5rO
            -----END PGP MESSAGE-----
          fp: E487A740E6312E16061F37E3E5A7009793E5E93B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
