name: capital
channels:
  - conda-forge
  - plotly
dependencies:
  - anyio=4.0.0
  - black=23.10.1
  - jupyter=1.0.0
  - matplotlib=3.8.0
  - numpy=1.26.0
  - pip=23.3.1
  - pandas=2.1.2
  - pandoc=3.1.3
  - pre-commit=3.5.0
  - pytest=7.4.3
  - pytest-cov
  - python=3.10.13
  - pyyaml=6.0.1
  - requests=2.31.0
  - ta-lib=0.4.28
  - yfinance=0.2.31
  - plotly=5.12.0
  - ipywidgets>=7.6
  - jupyterlab>=3
  - jupyter-dash
  - tenacity
  - tabulate
  - numba
